USE [master]
GO

/****** Object:  Database [Warehause]    Script Date: 29.11.2021 12:29:01 ******/
CREATE DATABASE [Warehause]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Warehause', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Warehause.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Warehause_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Warehause_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Warehause] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Warehause].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Warehause] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Warehause] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Warehause] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Warehause] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Warehause] SET ARITHABORT OFF 
GO

ALTER DATABASE [Warehause] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Warehause] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Warehause] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Warehause] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Warehause] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Warehause] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Warehause] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Warehause] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Warehause] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Warehause] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Warehause] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Warehause] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Warehause] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Warehause] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Warehause] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Warehause] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Warehause] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Warehause] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Warehause] SET  MULTI_USER 
GO

ALTER DATABASE [Warehause] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Warehause] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Warehause] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Warehause] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Warehause] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Warehause] SET QUERY_STORE = OFF
GO

USE [Warehause]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Warehause] SET  READ_WRITE 
GO


